version: "3.9"

services:  

  app_consumer:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      args:
        VARIANT: "17"
        INSTALL_MAVEN: "true"
        INSTALL_GRADLE: "false"
        NODE_VERSION: "none"
        GRADLE_VERSION: ""
    volumes:
      - .:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
